name: from_scrach
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install NPM
        run: |
          npm install
      - name: tests
        run: npm test
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: from_scratch_test
          path: |
            ./
